on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup WINE
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo mv winehq.key /usr/share/keyrings/winehq-archive.key
          wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo mv winehq-jammy.sources /etc/apt/sources.list.d/
          sudo apt update
          sudo apt install --install-recommends winehq-stable
      - name: Hello world action step
        uses: ./
        id: innostup
        with:
          file: 'InnoScript.iss'
          build-name: 'FinishedBuild'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: my-artifact
          path: ${{ steps.innostup.outputs.inno-output }}